#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    exclude = ["install.private", "install.multi"]

    args.backends_urls = "https://cloud.example.com"
    args.turn_endpoints = "turn:coturn.example.com:5349"
    args.turn_api_key = "turnserver"
    args.turn_secret = "v3rysecretpassword"
