#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..." --weight=1

ynh_restore_file --origin_path="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# RESTORE CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring configuration files..." --weight=1

# Signaling server
ynh_restore_file --origin_path="/etc/$app"
chown -R "$app:$app" "/etc/$app"

# Janus
ynh_restore_file --origin_path="/etc/janus/"

# Nats-server
ynh_restore_file --origin_path="/etc/nats-server.conf"
chown nats:nats "/etc/nats-server.conf"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "janus" --description="Janus WebRTC server for Nextcloud Talk" --log="/var/log/janus/janus.log"
yunohost service add "nats-server" --description="NATS server for Nextcloud signaling" --log="/var/log/nats-server.log"
yunohost service add "$app" --description="Nextcloud signaling server" --log="/var/log/$app/$app.log"

ynh_restore_file --origin_path="/etc/logrotate.d/$app"

#=================================================
# RESTORE LOG FILES
#=================================================
ynh_script_progression --message="Restoring log files..." --weight=1

ynh_restore_file --origin_path="/var/log/$app/" --not_mandatory

#=================================================
# RELOAD NGINX AND START SERVICES
#=================================================
ynh_script_progression --message="Reloading NGINX web server and starting services..." --weight=2

# Start services in order
ynh_systemctl --service="nats-server" --action="restart"
ynh_systemctl --service="janus" --action="restart"
ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Restoration completed for $app" --last
